"use client";

import Link from "next/link";

const GOLD = "#D4A843";

export default function ResearchPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-2xl font-mono font-black mb-2" style={{ color: GOLD }}>Research & Methodology</h1>
      <p className="text-[12px] font-mono text-white/55 mb-12">How the NTLGNC signal system works, validated, and evolves.</p>

      {/* The Model */}
      <section className="mb-12">
        <h2 className="text-sm font-mono font-bold text-white/80 mb-3">The Model</h2>
        <div className="text-[12px] font-mono leading-relaxed text-white/40 space-y-3">
          <p>
            NTLGNC signals are generated by a proprietary mathematical model that detects structural price patterns across cryptocurrency markets. The model operates on fractal principles — repeating patterns that appear at every time scale, from minutes to months.
          </p>
          <p>
            The model computes support and resistance zones using a multi-scale harmonic analysis. When price interacts with these zones under specific conditions, directional signals are generated. The model runs across 100+ cryptocurrency pairs simultaneously, detecting opportunities that would be invisible to human analysis.
          </p>
          <p>
            The core model is never modified by the AI system. It is the fixed mathematical foundation on which everything else is built.
          </p>
        </div>
      </section>

      {/* Validation */}
      <section className="mb-12">
        <h2 className="text-sm font-mono font-bold text-white/80 mb-3">Validation Framework</h2>
        <div className="text-[12px] font-mono leading-relaxed text-white/40 space-y-3">
          <p>
            Every strategy is validated using strict out-of-sample testing. Historical data is split: the first half is used for optimisation, the second half — data the system has never seen — is used for validation. Only strategies that perform well on unseen data are deployed.
          </p>
          <p>
            This approach was verified using synthetic random-walk data (prices with zero predictability). The system correctly found no edge in random data: in-sample Sharpe was high (pure overfitting), but out-of-sample Sharpe was -0.09 — statistically zero. This proves the validation gate works.
          </p>
          <p>
            When the same pipeline produces positive out-of-sample Sharpe ratios on real market data across 100+ coins and 5+ years of history, the edge is genuine market structure, not a statistical artefact.
          </p>
        </div>

        {/* Key stats box */}
        <div className="mt-4 p-4 rounded-xl grid grid-cols-3 gap-4" style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)" }}>
          {[
            { l: "OOS Consistency", v: "69/104 coins", d: "Positive Sharpe on unseen data" },
            { l: "Bootstrap Significance", v: "9 coins at p<0.05", d: "Verified via 10,000 random permutations" },
            { l: "Random Walk Check", v: "OOS SR: -0.09", d: "Confirms no look-ahead bias" },
          ].map(s => (
            <div key={s.l}>
              <div className="text-[8px] font-mono uppercase tracking-widest text-white/50">{s.l}</div>
              <div className="text-sm font-mono font-bold" style={{ color: GOLD }}>{s.v}</div>
              <div className="text-[9px] font-mono text-white/50 mt-0.5">{s.d}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Regime Analysis */}
      <section className="mb-12">
        <h2 className="text-sm font-mono font-bold text-white/80 mb-3">Regime Analysis</h2>
        <div className="text-[12px] font-mono leading-relaxed text-white/40 space-y-3">
          <p>
            Every signal is tagged with 16 market features at the moment of entry: volatility state, trend direction, time of day, price position in range, and more. These features are analysed to determine which market conditions produce the best and worst signal performance.
          </p>
          <p>
            Features are ranked by "spread" — the difference in performance between the best and worst conditions. Features with high spread AND stable rankings across in-sample and out-of-sample data are used as live filters. Features that invert (the best bucket in-sample becomes the worst out-of-sample) are retired.
          </p>
          <p>
            Currently, 6 features show perfect stability (ρ=1.0) between in-sample and out-of-sample: the system's performance in these conditions is consistent and predictable.
          </p>
        </div>
      </section>

      {/* AI Strategy Board */}
      <section className="mb-12">
        <h2 className="text-sm font-mono font-bold text-white/80 mb-3">AI Strategy Board</h2>
        <div className="text-[12px] font-mono leading-relaxed text-white/40 space-y-3">
          <p>
            Six AI models from different providers meet hourly to debate strategy modifications. Each model brings a different analytical perspective: quantitative rigour, risk assessment, contrarian thinking, cross-market context, parameter sensitivity, and timing effects.
          </p>
          <p>
            One model proposes a modification each hour. The others critique it. A supermajority (4/6) must agree before the proposal is tested. Accepted proposals are automatically backtested on data the models have never seen. Only improvements that exceed a 5% Sharpe improvement threshold are deployed.
          </p>
          <p>
            The AI models cannot modify the core mathematical model. They can only adjust filters, position sizing, hold duration, and hedging rules. This creates genuine recursive self-improvement with hard empirical checks at every step.
          </p>
        </div>
      </section>

      {/* Hedged Strategy */}
      <section className="mb-12">
        <h2 className="text-sm font-mono font-bold text-white/80 mb-3">Market-Neutral Hedging</h2>
        <div className="text-[12px] font-mono leading-relaxed text-white/40 space-y-3">
          <p>
            The system can pair opposite signals — a long on one coin with a short on another — to create market-neutral positions. The hedged return comes from relative price movement between the two coins, not from the market direction. This makes the strategy robust to market crashes and rallies alike.
          </p>
          <p>
            In backtesting across 33,000+ paired trades over 5 years, the hedged Sharpe ratio (1.25) significantly exceeds the unhedged ratio (0.08). This confirms the model's edge comes from relative pricing, not directional bets — a fundamentally more robust signal.
          </p>
        </div>
      </section>

      {/* Limitations */}
      <section className="mb-12">
        <h2 className="text-sm font-mono font-bold text-white/80 mb-3">Limitations & Risks</h2>
        <div className="text-[12px] font-mono leading-relaxed text-white/40 space-y-3">
          <p>
            Past performance does not guarantee future results. The model may encounter market conditions it has never seen. Cryptocurrency markets can experience extreme volatility, flash crashes, and liquidity gaps that are not reflected in historical data.
          </p>
          <p>
            The average return per trade is small (approximately 0.04%). The edge comes from consistency across thousands of trades. Individual trades will frequently lose. The win rate is approximately 51-52% — barely above a coin flip. The value is in the positive skew of returns: winners are larger than losers.
          </p>
          <p>
            Signals are informational only and do not constitute financial advice. Users should not risk capital they cannot afford to lose.
          </p>
        </div>
      </section>

      <div className="text-center pt-6 border-t" style={{ borderColor: "rgba(255,255,255,0.08)" }}>
        <Link href="/signals" className="px-6 py-3 rounded-lg text-sm font-mono font-bold inline-block" style={{ background: GOLD, color: "#000" }}>
          View Live Signals
        </Link>
      </div>
    </div>
  );
}
