export const metadata = {
  title: "Terms of Service — fracmap",
  description: "fracmap terms of service — conditions governing your use of the platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--text)]">
      <header className="border-b border-line">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="inline-block">
            <svg viewBox="0 0 320 64" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-[36px] w-auto"><defs><linearGradient id="lgGlow" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#f97316"/><stop offset="100%" stopColor="#fb923c"/></linearGradient><linearGradient id="lgText" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f0f0f8"/><stop offset="100%" stopColor="#c8c8d8"/></linearGradient><filter id="lgGl"><feGaussianBlur stdDeviation="3" result="b"/><feComposite in="SourceGraphic" in2="b" operator="over"/></filter></defs><g transform="translate(8,12)"><line x1="20" y1="20" x2="8" y2="8" stroke="#f97316" strokeWidth="1.5" opacity="0.4"/><line x1="20" y1="20" x2="34" y2="6" stroke="#f97316" strokeWidth="1.5" opacity="0.4"/><line x1="20" y1="20" x2="36" y2="28" stroke="#f97316" strokeWidth="1.5" opacity="0.3"/><line x1="20" y1="20" x2="6" y2="32" stroke="#f97316" strokeWidth="1.5" opacity="0.3"/><line x1="20" y1="20" x2="28" y2="38" stroke="#f97316" strokeWidth="1.5" opacity="0.25"/><circle cx="8" cy="8" r="2.5" fill="#f97316" opacity="0.6"/><circle cx="34" cy="6" r="2" fill="#f97316" opacity="0.5"/><circle cx="36" cy="28" r="1.8" fill="#f97316" opacity="0.4"/><circle cx="6" cy="32" r="2" fill="#f97316" opacity="0.45"/><circle cx="28" cy="38" r="1.5" fill="#f97316" opacity="0.35"/><circle cx="20" cy="20" r="5" fill="url(#lgGlow)" filter="url(#lgGl)"/><circle cx="20" cy="20" r="2.5" fill="#0b0b14"/><circle cx="20" cy="20" r="1.2" fill="#f97316"/></g><text x="60" y="44" fontFamily="'Chakra Petch',system-ui,sans-serif" fontWeight="700" fontSize="36" letterSpacing="0.18em" fill="url(#lgText)">FRACMAP</text><rect x="62" y="50" width="48" height="1.5" rx="0.75" fill="#f97316" opacity="0.7"/></svg>
          </a>
          <a href="/" className="text-xs text-brand hover:text-white transition-colors">← Back to dashboard</a>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10">
        <h1 className="text-2xl font-bold text-white mb-1">Terms of Service</h1>
        <p className="text-sm text-white/40 mb-8">Last updated: 10 February 2026</p>

        <div className="space-y-8 text-sm text-white/70 leading-relaxed">
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your use of the fracmap platform available at{" "}
            <a href="https://fracmap.com" className="text-brand hover:underline">https://fracmap.com</a>{" "}
            (the &ldquo;Service&rdquo;), operated by fracmap (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">1. Description of the Service</h2>
            <p>
              fracmap provides AI-generated trading signals (&ldquo;Signals&rdquo;) for financial instruments including, but not limited to, cryptocurrencies, foreign exchange currencies, commodities, and US and international equities and equity indices. The Signals are generated by third-party large language models (&ldquo;LLMs&rdquo;) that analyse historical price data. fracmap does not generate the Signals itself; it aggregates, scores, and presents outputs produced by third-party AI providers.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">2. Service tiers</h2>

            <h3 className="text-sm font-semibold text-white/90 mt-4 mb-1">Retail subscription</h3>
            <p>
              Individual users may subscribe to the Service for a fee of $20 per month (or such other price as published on the Website at the time of subscription). Retail subscribers access Signals, model performance data, and the Market Desk via the web-based user interface.
            </p>

            <h3 className="text-sm font-semibold text-white/90 mt-4 mb-1">Institutional service</h3>
            <p>
              Institutional clients may access a customised service that includes the ability to select specific instruments and signal periodicities, and to receive Signals programmatically via a JSON API as well as through the user interface. Institutional terms, pricing, and service-level agreements are agreed separately and may be subject to additional contractual terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">3. No financial advice</h2>
            <p>
              The Signals provided by fracmap do not constitute financial advice, investment advice, trading advice, or any other form of professional advice. Nothing on this platform should be interpreted as a recommendation to buy, sell, or hold any financial instrument.
            </p>
            <p className="mt-2">
              fracmap is an information service only. You should consult a qualified, regulated financial adviser before making any investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">4. Risk warning</h2>
            <div className="bg-down/5 border border-down/20 rounded-lg p-4 text-white/80">
              <p className="font-semibold text-white mb-2">⚠ Important: Capital at risk</p>
              <p>
                Trading and investing in financial instruments — including cryptocurrencies, currencies, commodities, and equities — carries a high level of risk. You may lose some or all of the money you invest. Past performance of any Signal, model, or strategy presented on this platform is not indicative of future results.
              </p>
              <p className="mt-2">
                While some Signals have historically demonstrated favourable outcomes, there is no guarantee that any Signal will be accurate or profitable in the future. Markets are unpredictable and AI models can and do produce incorrect predictions.
              </p>
              <p className="mt-2 font-semibold">
                You should only invest money that you can afford to lose entirely. All investment decisions are yours alone, and you assume full responsibility for any gains or losses that result from acting on Signals obtained through this Service.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">5. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by applicable law, fracmap, its directors, employees, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the Service, including but not limited to financial losses incurred as a result of acting on Signals.
            </p>
            <p className="mt-2">
              The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">6. Third-party AI providers</h2>
            <p>
              Signals are generated by third-party LLMs including, but not limited to, models provided by OpenAI, Anthropic, xAI, Google, Meta, Mistral, and DeepSeek. fracmap does not control or warrant the accuracy, reliability, or availability of these third-party models. Changes to third-party models, APIs, or policies may affect the Service without notice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">7. Your account</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. You must not share your account or API access with others unless expressly permitted under an institutional agreement. We reserve the right to suspend or terminate accounts that violate these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">8. Payment and cancellation</h2>
            <p>
              Subscription fees are billed monthly in advance. You may cancel your subscription at any time; cancellation takes effect at the end of the current billing period. Refunds are not provided for partial months. We reserve the right to change subscription pricing with 30 days&rsquo; notice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">9. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside ml-2 mt-1 space-y-0.5">
              <li>Redistribute, resell, or sublicense Signals without our written consent</li>
              <li>Reverse-engineer, scrape, or programmatically extract data beyond your authorised API access</li>
              <li>Use the Service for any unlawful purpose</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Misrepresent fracmap Signals as your own proprietary research</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">10. Intellectual property</h2>
            <p>
              All content on the Website — including design, code, text, charts, and branding — is owned by fracmap or its licensors and is protected by applicable intellectual property laws. Your subscription grants you a limited, non-exclusive, non-transferable licence to access the Service for your own use.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">11. Privacy</h2>
            <p>
              Your use of the Service is also governed by our{" "}
              <a href="/privacy" className="text-brand hover:underline">Privacy Policy</a>, which explains how we collect and use your data.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">12. Governing law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from these Terms or your use of the Service shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">13. Changes to these Terms</h2>
            <p>
              We may update these Terms from time to time. Where changes are material, we will notify you via the Website or by email. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-2">14. Contact</h2>
            <p>
              If you have questions about these Terms, contact us at{" "}
              <a href="mailto:support@fracmap.com" className="text-brand hover:underline">support@fracmap.com</a>.
            </p>
            <p className="mt-2">
              fracmap<br />
              13 Old Rectory Close<br />
              Instow, Devon EX39 4LY<br />
              United Kingdom
            </p>
          </section>
        </div>
      </main>

      <footer className="text-center py-6 text-white/20 text-[11px] border-t border-line mt-10">
        FRACMAP · AI Market Desk
      </footer>
    </div>
  );
}
